apiVersion: v1 
kind: ConfigMap 
metadata:
  name: containerlogs-config
data:
  DIAGNOSTIC_CONTAINERLOGS_LIST: kube-system
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: kubeobjects-config
data:
  DIAGNOSTIC_KUBEOBJECTS_LIST: kube-system/pod kube-system/service kube-system/deployment
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: nodelogs-config
data:
  DIAGNOSTIC_NODELOGS_LIST: /var/log/azure/cluster-provision.log /var/log/cloud-init.log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collectors-config
  namespace: aks-periscope
data:
  COLLECTOR_LIST: OSM # <custom flag>
